detection_rules:
  patterns:
    sections:
      contact:
        patterns:
          - 'contact\s*information'
          - 'personal\s*details'
          - '^\d{3}[-\s]?\d{3}[-\s]?\d{4}'
          - '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
          - '^linkedin\.com/in/[\w-]+$'
          - '^github\.com/[\w-]+$'
        required: true
      summary:
        patterns:
          - '^summary$'
          - 'professional\s+summary'
          - 'profile'
          - 'objective'
          - 'about\s+me'
          - 'career\s+objective'
        required: false
      skills:
        patterns:
          - '^skills$'
          - '^technical\s+skills$'
          - '^languages:'
          - '^frameworks\s+&\s+libraries:'
          - '^tools\s+&\s+ci/cd:'
          - '^testing:'
          - '^software\s+design\s+&\s+architecture:'
          - '^agile\s+methodologies:'
          - 'technical\s+skills'
          - 'skills(\s+&\s+competencies)?'
          - 'technologies(\s+used)?'
          - 'tools\s+&\s+technologies'
          - 'core\s+competencies'
          - 'expertise'
          - '^programming\s+languages$'
          - '^frameworks$'
          - '^tools$'
          - '^databases$'
          - '^methodologies$'
        required: true
      education:
        patterns:
          - '^education$'
          - 'education(\s+background)?'
          - 'academic(\s+background)?'
          - 'qualifications'
          - 'academic\s+history'
          - 'educational\s+qualifications'
          - 'bachelor\s+of\s+science'
          - 'national\s+certificate'
          - '^wethinkcode'
          - '^university\s+of'
          - '^college'
          - '^institute'
        required: true
      experience:
        patterns:
          - 'Work Experience'
          - 'Professional Experience'
          - 'Employment History'
          - 'Graduate Java Developer'
          - 'experience'
          - 'work\s+experience'
          - 'professional\s+experience'
          - 'employment\s+history'
          - 'career\s+history'
          - 'work\s+history'
          - 'job history'
          - 'career summary'
          - 'professional background'
          - 'positions held'
          - '[A-Z][a-z]+\s+[A-Z]?[a-z]*\s*Developer'
          - '[A-Z][a-z]+\s+Developer\s+\([A-Za-z]+\)'
          - '[A-Z][a-z]+\s+Training\s+Developer'
          - 'Technical\s+Mentor'
          - 'Trainee\s+Software\s+Developer'
          - '[A-Z][a-z]+\s+Engineer'
          - '[A-Z][a-z]+\s+Consultant'
          - '[A-Z][a-z]+\s+Analyst'
          - '[A-Z][a-z]+\s+Manager'
          - '[A-Z][a-z]+\s+Architect'
          - '[A-Z][a-z]+\s+Lead'
        required: true
      projects:
        patterns:
          - '^projects$'
          - '^technical\s+projects$'
          - 'portfolio'
          - 'technical\s+projects'
          - 'personal\s+projects'
          - 'key\s+projects'
          - '^[\w\s-]+\s+-\s+[\w\s]+(?:app|system|platform)$'
          - '^[\w\s-]+\s+-\s+[\w\s]+(?:game)$'
          - '^project\s+\d+:'
          - '^\d+\.\s+[\w\s-]+'
        required: false
      certifications:
        patterns:
          - '^achievements\s+&\s+certifications'
          - 'certifications?'
          - 'certificates?'
          - 'awards'
          - 'honors'
          - 'accomplishments'
          - '^hackerrank\s+certifications?:'
          - '^medallion'
        required: false
  settings:
    confidence_threshold: 0.2
    min_heading_size: 10
    fuzzy_match: true