detection_rules:
  patterns:
    contact:
      - "^[A-Z\\s]+$"  # Name in caps
      - "\\d{3}[-.]\\d{3}[-.]\\d{4}"  # Phone
      - "\\b[\\w\\.-]+@[\\w\\.-]+\\.[\\w]{2,4}\\b"  # Email
      - "linkedin\\.com"
      - "github\\.com"
    summary:
      - "summary"
      - "profile"
      - "objective"
    skills:
      - "technical skills"
      - "skills"
      - "competencies"
      - "technologies"
      - "tools & ci/cd"
      - "languages"
      - "frameworks"
    education:
      - "education"
      - "academic"
      - "university"
      - "college"
      - "school"
    experience:
      - "experience"
      - "employment"
      - "(software|java|python) developer"
      - "technical mentor"
      - "trainee"
    projects:
      - "technical projects"
      - "projects"
      - "portfolio"
    certifications:
      - "achievements & certifications"
      - "certifications"
      - "certificates"
  confidence_threshold: 0.6
  min_heading_size: 11